services:
  app:
    image: registry.digitalocean.com/fundme/fundme-app:latest
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      BLUEPRINT_DB_HOST: ${BLUEPRINT_DB_HOST}
      BLUEPRINT_DB_PORT:  ${BLUEPRINT_DB_PORT}
      BLUEPRINT_DB_USERNAME: ${BLUEPRINT_DB_USERNAME}
      BLUEPRINT_DB_ROOT_PASSWORD: ${BLUEPRINT_DB_ROOT_PASSWORD}
    depends_on:
      mongo_bp:
        condition: service_healthy
    networks:
      - blueprint
  mongo_bp:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BLUEPRINT_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BLUEPRINT_DB_ROOT_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:27017"
    volumes:
      - mongo_volume_bp:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - blueprint
  matchmaking:
    image: registry.digitalocean.com/fundme/matchmaking-service:latest
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2  # Suppress TensorFlow logging
    depends_on:
      - app
    networks:
      - blueprint

volumes:
  mongo_volume_bp:
networks:
  blueprint:
